language: java

jdk:
  - oraclejdk10

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "e73sqDM9emSib7nkGpAgRh2aJO++TWVHfJYWtmgOXXekg2tU4Z5lbqdviGX/MFQsjd6KTd92qOCcvmExEuPfD6ThuP0WSt3lzGdeBkwLq9fn4xGgEVRp+wrMBSu/jI4qdUNjYVJzvSsog1H0WMqPwG7iRxjSN5ZV2HaDwvV6kMA="

dist: xenial

addons:
  coverity_scan:
    project:
      name: "petrs/JCAlgTest"
      description: "Build submitted via Travis CI"
    notification_email: petr@svenda.com
    build_command_prepend: ""
    build_command:   "ant compile"
    branch_pattern: master
